version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: bot
    container_name: movieclub-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
      - TELEGRAM_WEBHOOK_SECRET_TOKEN=${TELEGRAM_WEBHOOK_SECRET_TOKEN}
      - KINOPOISK_API_VERSION=${KINOPOISK_API_VERSION:-v2.2}
      - KINOPOISK_API_KEY=${KINOPOISK_API_KEY}
      - KINOPOISK_API_URL=${KINOPOISK_API_URL:-https://kinopoiskapiunofficial.tech/api}
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=PRODUCTION
      - DOMAIN_ADDRESS=${DOMAIN_ADDRESS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
    networks:
      - movieclub-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:2000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TARGET: worker
    container_name: movieclub-worker
    restart: unless-stopped
    exclude_from_hc: true
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
      - REDIS_URL=${REDIS_URL}
      - KINOPOISK_API_VERSION=${KINOPOISK_API_VERSION:-v2.2}
      - KINOPOISK_API_KEY=${KINOPOISK_API_KEY}
      - KINOPOISK_API_URL=${KINOPOISK_API_URL:-https://kinopoiskapiunofficial.tech/api}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
    networks:
      - movieclub-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  movieclub-network:
    driver: bridge
